FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Generate Prisma client
RUN npx prisma generate

# Optional: install ts-node and nodemon globally if needed
RUN npm install -g ts-node-dev

EXPOSE 3000

# Use a shell to run prisma generate and migrations before starting the app
CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm run start:dev"]
